"""Render the three files that turn the agent source tree into a signed .exe:

1. `baked.py`          — Python constants injected into the agent package.
2. PyInstaller `.spec` — the build recipe.
3. `version_info.txt`  — Windows version resource (CompanyName, ProductName, etc).

All three are generated as plain strings from dataclass inputs. No Jinja
dependency; templating is small enough that f-strings + repr are clearer than
a template engine.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from .models import BuildSpec


# --- baked.py -----------------------------------------------------------------

_BAKED_HEADER = """\
# Auto-generated by the RMM build worker. DO NOT COMMIT.
#
# When this module is present, the agent reads its install config from these
# constants instead of looking for install_config.json on disk. That lets the
# standalone .exe be a truly portable single-file drop — no sidecar config.
#
# The enrollment token here is single-use and short-lived; after first launch
# the agent writes a permanent agent.json with its own long-lived token and
# this module is never consulted again.
"""


def _pyrepr(value: object) -> str:
    """repr() that's stable across Python versions for the types we emit."""
    if isinstance(value, (list, tuple)):
        return "[" + ", ".join(_pyrepr(v) for v in value) + "]"
    return repr(value)


def render_baked_module(spec: BuildSpec) -> str:
    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    lines = [
        _BAKED_HEADER,
        f"SERVER_URL = {_pyrepr(spec.server_url)}",
        f"ENROLLMENT_TOKEN = {_pyrepr(spec.enrollment_token)}",
        f"VERIFY_TLS = {_pyrepr(spec.verify_tls)}",
        f"TAGS = {_pyrepr(list(spec.tags))}",
        f"BUILD_ID = {_pyrepr(spec.build_id)}",
        f"AGENT_VERSION = {_pyrepr(spec.agent_version)}",
        f"GENERATED_AT = {_pyrepr(generated_at)}",
        "",
    ]
    return "\n".join(lines)


# --- PyInstaller .spec --------------------------------------------------------

_SPEC_TEMPLATE = """\
# -*- mode: python ; coding: utf-8 -*-
# Auto-generated by the RMM build worker.

block_cipher = None

a = Analysis(
    ['rmm_agent/__main__.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports={hidden_imports!r},
    hookspath=[],
    hooksconfig={{}},
    runtime_hooks=[],
    excludes=['tkinter', 'unittest', 'pydoc_data'],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name={exe_name!r},
    debug=False,
    bootloader_ignore_signals=False,
    strip={strip!r},
    upx={upx!r},
    upx_exclude=[],
    runtime_tmpdir=None,
    console={console!r},
    disable_windowed_traceback=False,
    target_arch='x86_64',
    codesign_identity=None,
    entitlements_file=None,
    icon={icon!r},
    version={version!r},
)
"""

_HIDDEN_IMPORTS = [
    # Explicit list so PyInstaller doesn't silently drop a transitive import.
    # These are the runtime deps of the agent as of MVP; extend when we add more.
    "psutil",
    "websockets",
    "websockets.asyncio.client",
    "httpx",
]


def render_spec_file(spec: BuildSpec, *, exe_name: str = "rmm-agent") -> str:
    # PyInstaller reads these paths relative to the spec file's directory,
    # which is the temp build dir. We emit basenames only.
    icon = "rmm-agent.ico" if spec.icon_path else None
    version = "version_info.txt"
    return _SPEC_TEMPLATE.format(
        hidden_imports=_HIDDEN_IMPORTS,
        exe_name=exe_name,
        strip=spec.strip,
        upx=spec.upx,
        console=spec.console,
        icon=icon,
        version=version,
    )


# --- version_info.txt ---------------------------------------------------------

_VERSION_TEMPLATE = """\
# Auto-generated by the RMM build worker.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={filevers},
    prodvers={prodvers},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0),
  ),
  kids=[
    StringFileInfo([
      StringTable(
        '040904B0',
        [
          StringStruct('CompanyName', {company!r}),
          StringStruct('FileDescription', {file_description!r}),
          StringStruct('FileVersion', {file_version!r}),
          StringStruct('InternalName', 'rmm-agent'),
          StringStruct('LegalCopyright', {legal_copyright!r}),
          StringStruct('OriginalFilename', 'rmm-agent.exe'),
          StringStruct('ProductName', {product_name!r}),
          StringStruct('ProductVersion', {file_version!r}),
        ],
      ),
    ]),
    VarFileInfo([VarStruct('Translation', [1033, 1200])]),
  ],
)
"""

_VERSION_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)(?:\.(\d+))?")


def _version_tuple(version: str) -> tuple[int, int, int, int]:
    m = _VERSION_RE.match(version)
    if not m:
        return (0, 0, 0, 0)
    major, minor, patch, build = m.groups()
    return (int(major), int(minor), int(patch), int(build or 0))


def render_version_info(spec: BuildSpec) -> str:
    v = _version_tuple(spec.agent_version)
    return _VERSION_TEMPLATE.format(
        filevers=v,
        prodvers=v,
        file_version=f"{v[0]}.{v[1]}.{v[2]}.{v[3]}",
        company=spec.company_name,
        product_name=spec.product_name,
        file_description=spec.file_description,
        legal_copyright=spec.legal_copyright or f"(c) {datetime.now(timezone.utc).year} {spec.company_name}",
    )


# --- Orchestration ------------------------------------------------------------

def stage_build_tree(spec: BuildSpec, dest: Path) -> None:
    """Copy the agent source into `dest` and write all generated files.

    After this returns, `dest` is a self-contained PyInstaller workdir:
      dest/
        rmm_agent/           (copied from agent source)
        rmm_agent/baked.py   (generated)
        requirements.txt     (copied)
        rmm-agent.spec       (generated)
        version_info.txt     (generated)
        rmm-agent.ico        (copied, if spec.icon_path set)
    """
    import shutil

    src = spec.agent_source_dir
    if not (src / "rmm_agent" / "__main__.py").is_file():
        raise FileNotFoundError(
            f"agent source not found at {src}; set BuildSpec.agent_source_dir"
        )

    dest.mkdir(parents=True, exist_ok=True)

    # Copy the package and requirements, excluding caches and any pre-existing baked.py
    shutil.copytree(
        src / "rmm_agent",
        dest / "rmm_agent",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "baked.py"),
    )
    req = src / "requirements.txt"
    if req.is_file():
        shutil.copy2(req, dest / "requirements.txt")

    # Write generated files
    (dest / "rmm_agent" / "baked.py").write_text(render_baked_module(spec), encoding="utf-8")
    (dest / "rmm-agent.spec").write_text(render_spec_file(spec), encoding="utf-8")
    (dest / "version_info.txt").write_text(render_version_info(spec), encoding="utf-8")

    if spec.icon_path is not None:
        if not spec.icon_path.is_file():
            raise FileNotFoundError(f"icon not found: {spec.icon_path}")
        shutil.copy2(spec.icon_path, dest / "rmm-agent.ico")
